/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    AFloatButton: typeof import('ant-design-vue/es')['FloatButton']
    AFloatButtonGroup: typeof import('ant-design-vue/es')['FloatButtonGroup']
    APopover: typeof import('ant-design-vue/es')['Popover']
    AQrcode: typeof import('ant-design-vue/es')['QRCode']
    ASegmented: typeof import('ant-design-vue/es')['Segmented']
    ASpace: typeof import('ant-design-vue/es')['Space']
    ATag: typeof import('ant-design-vue/es')['Tag']
    ATooltip: typeof import('ant-design-vue/es')['Tooltip']
    ATour: typeof import('ant-design-vue/es')['Tour']
    ATypography: typeof import('ant-design-vue/es')['Typography']
    ATypographyParagraph: typeof import('ant-design-vue/es')['TypographyParagraph']
    AWatermark: typeof import('ant-design-vue/es')['Watermark']
    CommentOutlined: typeof import('@ant-design/icons-vue')['CommentOutlined']
    CustomerServiceOutlined: typeof import('@ant-design/icons-vue')['CustomerServiceOutlined']
    EllipsisOutlined: typeof import('@ant-design/icons-vue')['EllipsisOutlined']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
